version: '3.7'
services:
  portfolio:
    image: portfolio-i
    container_name: portfolio-c
    restart: unless-stopped
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - out:/usr/share/nginx/html/