version: '3'
services:
  app:
    build: ./
    ports:
      - 3000:3000
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/letsencrypt:/etc/letsencrypt/
 