import Head from 'next/head';
import { AiFillLinkedin, AiFillGithub } from 'react-icons/ai';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { useState } from 'react';
import deved from '../public/dev-ed-wave.png';
import code from '../public/code.png';
import design from '../public/design.png';
import consulting from '../public/consulting.png';
import Image from 'next/image';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import subject from '../public/subject.png';
import computer from '../public/computer.svg';
import useSWR from 'swr';

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  const { data, error } = useSWR('bgImg', async () => {
    const response = await fetch(
      'https://api.nasa.gov/planetary/apod?api_key=JQiPrXDedvAVpI2F9L2hUXxtutTatBKMDIFGZleL'
    );
    const data = response.json();

    return data;
  });
  const myStyle = {
    background: `url(${data?.url}) 0% 0% / cover no-repeat`,
    // backgroundSize: 'cover',
  };
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Tanchohang A. Limbu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className=" font-mono bg-myblue text-myblack  dark:bg-[#0b2236]">
        {/* <div className="email rotate-90 fixed bottom-0 right-[1px] py-[200px]">
          <a
            href="mailto:tanchohang@gmail.com"
            className=" hover:text-teal-600 tracking-widest after:w-[1px] after:h-[90px] after:bg-blue-700  "
          >
            tanchohang@gmail.com
          </a>
        </div> */}
        {/* {darkMode && (
          <section
            className="min-h-screen w-[100vw] fixed top-0 left-0 opacity-10 z-0"
            style={myStyle}
          ></section>
        )} */}
        <section className="min-h-screen relative">
          <section className="h-[10vh]">
            <nav className="py-5 flex justify-between dark:text-white shadow-2xl w-[100vw] px-10">
              <div className="flex gap-3">
                {/* <Image
                src={subject}
                alt=""
                className="rounded-full bg-teal-300 max-h-[30px] max-w-[30px]"
              /> */}
                {/* <h1 className=" font-bungee text-6xl text-teal-500 animate-wiggle">
                  TAN
                </h1> */}

                <div className=" rounded-md relative w-[40px] h-[40px] md:w-[80px] md:h-[80px] ">
                  <Image
                    src={computer}
                    layout="fill"
                    alt=""
                    fill="cover"
                    className="animate-wiggle sepia"
                  />
                </div>
              </div>
              <ul className="flex items-center">
                <li>
                  <BsFillMoonStarsFill
                    onClick={() => setDarkMode(!darkMode)}
                    className=" cursor-pointer text-2xl"
                  />
                </li>
                <li>
                  <a
                    className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                    href="#"
                  >
                    Resume
                  </a>
                </li>
              </ul>
            </nav>
          </section>
          <div className="h-[90vh] w-[90vw] mx-auto flex flex-col justify-center md:justify-between md:items-center md:flex-row px-20">
            <div className=" animate-slideLeft md:grow text-center md:text-left mb-20">
              <p className="text-teal-600 font-medium">Hi, I am</p>
              <h2 className="text-3xl md:text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 ">
                Tanchohang A. Limbu
              </h2>
              <div className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl md:text-xl text-center md:text-start">
                <span>Software Engineer</span>
                <ul className="flex justify-center md:justify-start list-none">
                  <li>
                    <span className=" text-pink-400">Front</span>-End |
                  </li>
                  <li>
                    <span className=" text-lime-400"> Back</span>-End |
                  </li>
                  <li>
                    <span className="text-indigo-400">App</span> developer
                  </li>
                </ul>
              </div>
              <div className="text-5xl flex md:justify-start justify-center gap-5 py-3 text-gray-600 dark:text-gray-400 ">
                <a href="https://www.linkedin.com/in/tanchohang">
                  <AiFillLinkedin />
                </a>
                <a href="https://github.com/tanchohang">
                  <AiFillGithub />
                </a>
              </div>
            </div>

            <div className=" rounded-md relative w-[200px] h-[200px] md:w-[400px] md:h-[400px] ">
              <Image
                src={computer}
                layout="fill"
                alt=""
                fill="cover"
                className="animate-slideRight sepia"
              />
            </div>
          </div>
        </section>

        <div className="px-20">
          {/* My skills */}
          <section className="">
            <div>
              <h3 className="text-3xl py-1 dark:text-white ">My Skills</h3>
            </div>
            <div className="lg:flex gap-10">
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:text-white dark:bg-[#0a1930] flex-1 dark:ring-1 dark:ring-teal-500">
                <Image src={design} width={100} height={100} alt="" />
                <h3 className="text-lg font-medium pt-8 pb-2  ">
                  Software Development
                </h3>
                <p className="py-2">Experienced in programing languages</p>
                <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
                <p className="text-gray-800 py-1">Photoshop</p>
                <p className="text-gray-800 py-1">Illustrator</p>
                <p className="text-gray-800 py-1">Figma</p>
                <p className="text-gray-800 py-1">Indesign</p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:text-white dark:bg-[#0a1930] flex-1 dark:ring-1 dark:ring-teal-500">
                <Image src={code} width={100} height={100} alt="" />
                <h3 className="text-lg font-medium pt-8 pb-2 ">
                  Code your dream project
                </h3>
                <p className="py-2">
                  Do you have an idea for your next great website? Let&apos;s
                  make it a reality.
                </p>
                <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
                <p className="text-gray-800 py-1">Photoshop</p>
                <p className="text-gray-800 py-1">Illustrator</p>
                <p className="text-gray-800 py-1">Figma</p>
                <p className="text-gray-800 py-1">Indesign</p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:text-white dark:bg-[#0a1930] flex-1 dark:ring-1 dark:ring-teal-500">
                <Image src={consulting} width={100} height={100} alt="" />
                <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
                <p className="py-2">
                  Are you interested in feedback for your current project? I can
                  give you tips and tricks to level it up.
                </p>
                <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
                <p className="text-gray-800 py-1">Photoshop</p>
                <p className="text-gray-800 py-1">Illustrator</p>
                <p className="text-gray-800 py-1">Figma</p>
                <p className="text-gray-800 py-1">Indesign</p>
              </div>
            </div>
          </section>

          <section className=" ">
            <div>
              <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                Since the beginning of my journey as a freelance designer and
                developer, I&apos;ve done remote work for
                <span className="text-teal-500"> agencies </span>
                consulted for <span className="text-teal-500">startups </span>
                and collaborated with talanted people to create digital products
                for both business and consumer use.
              </p>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                I offer from a wide range of services, including brand design,
                programming and teaching.
              </p>
            </div>
            <div className="flex flex-col gap-10  lg:flex-row lg:flex-wrap">
              <div className="basis-1/3 flex-1 ">
                <Image
                  className="rounded-lg object-cover"
                  width={'100%'}
                  height={'100%'}
                  layout="responsive"
                  src={web1}
                  alt=""
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  className="rounded-lg object-cover"
                  width={'100%'}
                  height={'100%'}
                  layout="responsive"
                  src={web2}
                  alt=""
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  className="rounded-lg object-cover"
                  width={'100%'}
                  height={'100%'}
                  layout="responsive"
                  src={web3}
                  alt=""
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  className="rounded-lg object-cover"
                  width={'100%'}
                  height={'100%'}
                  layout="responsive"
                  src={web4}
                  alt=""
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  className="rounded-lg object-cover"
                  width={'100%'}
                  height={'100%'}
                  layout="responsive"
                  src={web5}
                  alt=""
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  className="rounded-lg object-cover"
                  width={'100%'}
                  height={'100%'}
                  layout="responsive"
                  src={web6}
                  alt=""
                />
              </div>
            </div>
          </section>
          <section className="mt-20 ">
            <p className=" text-zinc-100">
              <a href="https://www.freepik.com/free-vector/retro-computer-concept-illustration_32318415.htm#query=old%20computer&position=7&from_view=search&track=sph">
                Image by storyset
              </a>{' '}
              on Freepik
            </p>
            <p className="text-center text-teal-500">
              <span>Designed & Built by Tanchohang Angdembe Limbu</span>
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
